name: Android CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Очистка повреждённых файлов SDK
      - name: Clean SDK cache
        run: |
          rm -rf $ANDROID_HOME/platforms
          rm -rf $ANDROID_HOME/build-tools
          rm -rf $ANDROID_HOME/system-images

      # Принятие лицензий и установка нужных компонентов SDK
      - name: Install specific SDK platforms
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-34" "build-tools;34.0.0"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload build logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            ~/.gradle/daemon/*/daemon-*.log
            app/build/reports/