name: Android Debug Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run lint
        run: ./gradlew lint
      - name: Build with Gradle (with logs)
        run: ./gradlew assembleDebug --stacktrace --info > build.log 2>&1
      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
      - name: Upload intermediate resources on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: merged-resources
          path: app/build/intermediates/merged_res/